"""Render the traceability matrix from the same catalog served by the API."""

import argparse
from pathlib import Path

from jocky_control_plane.coverage import load_coverage

ROOT = Path(__file__).resolve().parents[1]


def render() -> str:
    lines = [
        "# Requirement traceability",
        "",
        "JOCKY — One Language. Every Endpoint. No Noise.",
        "",
        "Generated by `make coverage` from the control-plane requirement catalog. "
        "The Architecture / Coverage page consumes this same catalog.",
        "",
        "Status describes implementation, not importance. PLANNED = specified only; "
        "SCAFFOLDED = boundaries/build exist; IMPLEMENTED = code exists but acceptance incomplete; "
        "VERIFIED = scoped acceptance recorded; "
        "BLOCKED_ENVIRONMENT = external prerequisite absent; "
        "PARTIAL = only the stated subset is implemented; NOT_TESTED = acceptance not executed. "
        "P0 verification does not certify P1–P10 features. Demo evidence in PLANNED rows is an "
        "acceptance target, not a claim that the demo works.",
        "",
        "Restricted techniques remain visible through safe prototype mappings; the prohibited "
        "attack capability itself will never be an implementation target.",
        "",
        "| ID / requirement | Implementation | Subsystem / phase | Demo evidence / acceptance | "
        "Current status | Safety / environment note |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for item in load_coverage():
        cells = [
            f"{item.id}: {item.title}",
            item.implementation,
            f"{item.subsystem} / {item.phase}",
            item.demo_evidence,
            item.status,
            item.safety_environment_note,
        ]
        lines.append("| " + " | ".join(c.replace("|", "\\|") for c in cells) + " |")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = ROOT / "docs/REQUIREMENT_TRACEABILITY.md"
    content = render()
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8") != content:
            raise SystemExit("Traceability drift. Run make coverage.")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
