"""durable_agent_receipts

Revision ID: 44b0cc037309
Revises: aee790e3e6bd
"""

import sqlalchemy as sa
from alembic import op

revision = "44b0cc037309"
down_revision = "aee790e3e6bd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_receipts",
        sa.Column("endpoint_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("frame_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_id"], ["endpoints.id"], name=op.f("fk_agent_receipts_endpoint_id_endpoints")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_receipts")),
        sa.UniqueConstraint("endpoint_id", "sequence", name=op.f("uq_agent_receipts_endpoint_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("agent_receipts")
    # ### end Alembic commands ###
