"""distributed_control_plane

Revision ID: aee790e3e6bd
Revises: 0001_foundation
"""

import sqlalchemy as sa
from alembic import op

revision = "aee790e3e6bd"
down_revision = "0001_foundation"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("audit_sequence", sa.Integer(), nullable=False),
        sa.Column("audit_head", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "audit_events",
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("integrity_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_audit_events_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
        sa.UniqueConstraint(
            "organization_id", "sequence", name=op.f("uq_audit_events_organization_id")
        ),
    )
    op.create_table(
        "cases",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "CLOSED",
                "CREATED",
                "QUEUED",
                "DISPATCHED",
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "PARTIAL",
                "CANCEL_REQUESTED",
                "CANCELLED",
                "INCOMPATIBLE",
                "OFFLINE",
                "ONLINE",
                "REVOKED",
                name="state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_cases_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cases")),
    )
    op.create_index(op.f("ix_cases_organization_id"), "cases", ["organization_id"], unique=False)
    op.create_table(
        "endpoints",
        sa.Column("hostname", sa.String(length=255), nullable=False),
        sa.Column("target_os", sa.String(length=16), nullable=False),
        sa.Column("target_arch", sa.String(length=16), nullable=False),
        sa.Column("agent_version", sa.String(length=64), nullable=False),
        sa.Column("identity", sa.String(length=128), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("certificate_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("execution_modes", sa.JSON(), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sequence", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "CLOSED",
                "CREATED",
                "QUEUED",
                "DISPATCHED",
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "PARTIAL",
                "CANCEL_REQUESTED",
                "CANCELLED",
                "INCOMPATIBLE",
                "OFFLINE",
                "ONLINE",
                "REVOKED",
                name="state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_endpoints_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_endpoints")),
        sa.UniqueConstraint(
            "certificate_fingerprint", name=op.f("uq_endpoints_certificate_fingerprint")
        ),
        sa.UniqueConstraint("identity", name=op.f("uq_endpoints_identity")),
    )
    op.create_index(
        op.f("ix_endpoints_organization_id"), "endpoints", ["organization_id"], unique=False
    )
    op.create_table(
        "event_outbox",
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("resource_id", sa.Uuid(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_event_outbox_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_outbox")),
        sa.UniqueConstraint(
            "organization_id", "sequence", name=op.f("uq_event_outbox_organization_id")
        ),
    )
    op.create_index(
        op.f("ix_event_outbox_organization_id"), "event_outbox", ["organization_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "ADMIN", "ANALYST", "VIEWER", name="role", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_users_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("organization_id", "username", name=op.f("uq_users_organization_id")),
    )
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_table(
        "endpoint_enrollments",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("endpoint_id", sa.Uuid(), nullable=True),
        sa.Column("capabilities", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_id"],
            ["endpoints.id"],
            name=op.f("fk_endpoint_enrollments_endpoint_id_endpoints"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_endpoint_enrollments_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_endpoint_enrollments")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_endpoint_enrollments_token_hash")),
    )
    op.create_index(
        op.f("ix_endpoint_enrollments_organization_id"),
        "endpoint_enrollments",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "findings",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("rule_key", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("observation_ids", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_findings_case_id_cases")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_findings_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
        sa.UniqueConstraint("case_id", "rule_key", name=op.f("uq_findings_case_id")),
    )
    op.create_index(
        op.f("ix_findings_organization_id"), "findings", ["organization_id"], unique=False
    )
    op.create_table(
        "scripts",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_scripts_case_id_cases")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_scripts_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scripts")),
    )
    op.create_index(
        op.f("ix_scripts_organization_id"), "scripts", ["organization_id"], unique=False
    )
    op.create_table(
        "session_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_session_tokens_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_session_tokens_token_hash")),
    )
    op.create_table(
        "script_versions",
        sa.Column("script_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_script_versions_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["script_id"], ["scripts.id"], name=op.f("fk_script_versions_script_id_scripts")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_script_versions")),
        sa.UniqueConstraint("script_id", "version", name=op.f("uq_script_versions_script_id")),
    )
    op.create_index(
        op.f("ix_script_versions_organization_id"),
        "script_versions",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "compilations",
        sa.Column("script_version_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "CLOSED",
                "CREATED",
                "QUEUED",
                "DISPATCHED",
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "PARTIAL",
                "CANCEL_REQUESTED",
                "CANCELLED",
                "INCOMPATIBLE",
                "OFFLINE",
                "ONLINE",
                "REVOKED",
                name="state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("outputs", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_compilations_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["script_version_id"],
            ["script_versions.id"],
            name=op.f("fk_compilations_script_version_id_script_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_compilations")),
    )
    op.create_index(
        op.f("ix_compilations_organization_id"), "compilations", ["organization_id"], unique=False
    )
    op.create_table(
        "benchmark_runs",
        sa.Column("compilation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "CLOSED",
                "CREATED",
                "QUEUED",
                "DISPATCHED",
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "PARTIAL",
                "CANCEL_REQUESTED",
                "CANCELLED",
                "INCOMPATIBLE",
                "OFFLINE",
                "ONLINE",
                "REVOKED",
                name="state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("measurements", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["compilation_id"],
            ["compilations.id"],
            name=op.f("fk_benchmark_runs_compilation_id_compilations"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_benchmark_runs_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_benchmark_runs")),
    )
    op.create_index(
        op.f("ix_benchmark_runs_organization_id"),
        "benchmark_runs",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "execution_plans",
        sa.Column("compilation_id", sa.Uuid(), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["compilation_id"],
            ["compilations.id"],
            name=op.f("fk_execution_plans_compilation_id_compilations"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_execution_plans_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_execution_plans")),
    )
    op.create_index(
        op.f("ix_execution_plans_organization_id"),
        "execution_plans",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "hunts",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("compilation_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint_ids", sa.JSON(), nullable=False),
        sa.Column("execution_mode", sa.String(length=16), nullable=False),
        sa.Column("diverse", sa.Boolean(), nullable=False),
        sa.Column("retry_limit", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "CLOSED",
                "CREATED",
                "QUEUED",
                "DISPATCHED",
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "PARTIAL",
                "CANCEL_REQUESTED",
                "CANCELLED",
                "INCOMPATIBLE",
                "OFFLINE",
                "ONLINE",
                "REVOKED",
                name="state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_hunts_case_id_cases")),
        sa.ForeignKeyConstraint(
            ["compilation_id"],
            ["compilations.id"],
            name=op.f("fk_hunts_compilation_id_compilations"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_hunts_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hunts")),
    )
    op.create_index(op.f("ix_hunts_organization_id"), "hunts", ["organization_id"], unique=False)
    op.create_table(
        "variants",
        sa.Column("compilation_id", sa.Uuid(), nullable=False),
        sa.Column("seed", sa.String(length=16), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["compilation_id"],
            ["compilations.id"],
            name=op.f("fk_variants_compilation_id_compilations"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_variants_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_variants")),
    )
    op.create_index(
        op.f("ix_variants_organization_id"), "variants", ["organization_id"], unique=False
    )
    op.create_table(
        "compatibility_runs",
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("observations", sa.JSON(), nullable=False),
        sa.Column("recorded_by", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_compatibility_runs_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by"], ["users.id"], name=op.f("fk_compatibility_runs_recorded_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"], ["variants.id"], name=op.f("fk_compatibility_runs_variant_id_variants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_compatibility_runs")),
    )
    op.create_index(
        op.f("ix_compatibility_runs_organization_id"),
        "compatibility_runs",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "jobs",
        sa.Column("hunt_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=True),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("retry_of", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "CLOSED",
                "CREATED",
                "QUEUED",
                "DISPATCHED",
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "PARTIAL",
                "CANCEL_REQUESTED",
                "CANCELLED",
                "INCOMPATIBLE",
                "OFFLINE",
                "ONLINE",
                "REVOKED",
                name="state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("envelope", sa.JSON(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("progress", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_id"], ["endpoints.id"], name=op.f("fk_jobs_endpoint_id_endpoints")
        ),
        sa.ForeignKeyConstraint(["hunt_id"], ["hunts.id"], name=op.f("fk_jobs_hunt_id_hunts")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_jobs_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["execution_plans.id"], name=op.f("fk_jobs_plan_id_execution_plans")
        ),
        sa.ForeignKeyConstraint(["retry_of"], ["jobs.id"], name=op.f("fk_jobs_retry_of_jobs")),
        sa.ForeignKeyConstraint(
            ["variant_id"], ["variants.id"], name=op.f("fk_jobs_variant_id_variants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("hunt_id", "endpoint_id", "attempt", name=op.f("uq_jobs_hunt_id")),
    )
    op.create_index(op.f("ix_jobs_organization_id"), "jobs", ["organization_id"], unique=False)
    op.create_table(
        "artifacts",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_artifacts_case_id_cases")),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_artifacts_job_id_jobs")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_artifacts_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
    )
    op.create_index(
        op.f("ix_artifacts_organization_id"), "artifacts", ["organization_id"], unique=False
    )
    op.create_table(
        "evidence_manifests",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("signature_verified", sa.Boolean(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_evidence_manifests_job_id_jobs")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_evidence_manifests_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence_manifests")),
        sa.UniqueConstraint("job_id", name=op.f("uq_evidence_manifests_job_id")),
    )
    op.create_index(
        op.f("ix_evidence_manifests_organization_id"),
        "evidence_manifests",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "observations",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint_id", sa.Uuid(), nullable=False),
        sa.Column("producer_id", sa.String(length=128), nullable=False),
        sa.Column("collector", sa.String(length=128), nullable=False),
        sa.Column("integrity_hash", sa.String(length=64), nullable=False),
        sa.Column("document", sa.JSON(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_observations_case_id_cases")
        ),
        sa.ForeignKeyConstraint(
            ["endpoint_id"], ["endpoints.id"], name=op.f("fk_observations_endpoint_id_endpoints")
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_observations_job_id_jobs")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_observations_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observations")),
        sa.UniqueConstraint("endpoint_id", "producer_id", name=op.f("uq_observations_endpoint_id")),
    )
    op.create_index(op.f("ix_observations_case_id"), "observations", ["case_id"], unique=False)
    op.create_index(
        op.f("ix_observations_organization_id"), "observations", ["organization_id"], unique=False
    )
    op.create_table(
        "reports",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "CLOSED",
                "CREATED",
                "QUEUED",
                "DISPATCHED",
                "RUNNING",
                "SUCCESS",
                "FAILED",
                "PARTIAL",
                "CANCEL_REQUESTED",
                "CANCELLED",
                "INCOMPATIBLE",
                "OFFLINE",
                "ONLINE",
                "REVOKED",
                name="state",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("format", sa.String(length=16), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"], ["artifacts.id"], name=op.f("fk_reports_artifact_id_artifacts")
        ),
        sa.ForeignKeyConstraint(["case_id"], ["cases.id"], name=op.f("fk_reports_case_id_cases")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reports_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(
        op.f("ix_reports_organization_id"), "reports", ["organization_id"], unique=False
    )
    op.create_table(
        "timeline_events",
        sa.Column("case_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint_id", sa.Uuid(), nullable=False),
        sa.Column("observation_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_basis", sa.String(length=16), nullable=False),
        sa.Column("collector", sa.String(length=128), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("type", sa.String(length=128), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("simulation", sa.Boolean(), nullable=False),
        sa.Column("simulation_label", sa.String(length=128), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"], ["cases.id"], name=op.f("fk_timeline_events_case_id_cases")
        ),
        sa.ForeignKeyConstraint(
            ["endpoint_id"], ["endpoints.id"], name=op.f("fk_timeline_events_endpoint_id_endpoints")
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
            name=op.f("fk_timeline_events_observation_id_observations"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_timeline_events_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_timeline_events")),
        sa.UniqueConstraint("observation_id", name=op.f("uq_timeline_events_observation_id")),
    )
    op.create_index(
        op.f("ix_timeline_events_case_id"), "timeline_events", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_timeline_events_organization_id"),
        "timeline_events",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_timeline_events_timestamp"), "timeline_events", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_timeline_events_timestamp"), table_name="timeline_events")
    op.drop_index(op.f("ix_timeline_events_organization_id"), table_name="timeline_events")
    op.drop_index(op.f("ix_timeline_events_case_id"), table_name="timeline_events")
    op.drop_table("timeline_events")
    op.drop_index(op.f("ix_reports_organization_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_observations_organization_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_case_id"), table_name="observations")
    op.drop_table("observations")
    op.drop_index(op.f("ix_evidence_manifests_organization_id"), table_name="evidence_manifests")
    op.drop_table("evidence_manifests")
    op.drop_index(op.f("ix_artifacts_organization_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_jobs_organization_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_compatibility_runs_organization_id"), table_name="compatibility_runs")
    op.drop_table("compatibility_runs")
    op.drop_index(op.f("ix_variants_organization_id"), table_name="variants")
    op.drop_table("variants")
    op.drop_index(op.f("ix_hunts_organization_id"), table_name="hunts")
    op.drop_table("hunts")
    op.drop_index(op.f("ix_execution_plans_organization_id"), table_name="execution_plans")
    op.drop_table("execution_plans")
    op.drop_index(op.f("ix_benchmark_runs_organization_id"), table_name="benchmark_runs")
    op.drop_table("benchmark_runs")
    op.drop_index(op.f("ix_compilations_organization_id"), table_name="compilations")
    op.drop_table("compilations")
    op.drop_index(op.f("ix_script_versions_organization_id"), table_name="script_versions")
    op.drop_table("script_versions")
    op.drop_table("session_tokens")
    op.drop_index(op.f("ix_scripts_organization_id"), table_name="scripts")
    op.drop_table("scripts")
    op.drop_index(op.f("ix_findings_organization_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(
        op.f("ix_endpoint_enrollments_organization_id"), table_name="endpoint_enrollments"
    )
    op.drop_table("endpoint_enrollments")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_event_outbox_organization_id"), table_name="event_outbox")
    op.drop_table("event_outbox")
    op.drop_index(op.f("ix_endpoints_organization_id"), table_name="endpoints")
    op.drop_table("endpoints")
    op.drop_index(op.f("ix_cases_organization_id"), table_name="cases")
    op.drop_table("cases")
    op.drop_table("audit_events")
    op.drop_table("organizations")
    # ### end Alembic commands ###
